# Generated by Django 4.2.6 on 2023-11-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=10)),
                ('Rating', models.CharField(max_length=1)),
                ('Link', models.CharField(max_length=255)),
                ('Site', models.CharField(max_length=255)),
            ],
        ),
    ]
